Style/IndentationConsistency:
  EnforcedStyle: rails

Lint/AssignmentInCondition:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/TrailingComma:
  EnforcedStyleForMultiline: comma
