terms:
  - term: Public Domain
    id:   http://creativecommons.org/publicdomain/mark/1.0/
  - term: CC0
    id:   http://creativecommons.org/publicdomain/zero/1.0/
  - term: CC-BY
    id:   http://creativecommons.org/licenses/by/4.0/
  - term: CC-BY-SA
    id:   http://creativecommons.org/licenses/by-sa/4.0/
  - term: CC-BY-ND
    id:   http://creativecommons.org/licenses/by-nd/4.0/
  - term: CC-BY-NC
    id:   http://creativecommons.org/licenses/by-nc/4.0/
  - term: CC-BY-NC-SA
    id:   http://creativecommons.org/licenses/by-nc-sa/4.0/
  - term: CC-BY-NC-ND
    id:   http://creativecommons.org/licenses/by-nc-nd/4.0/
  - term: Education Use Permitted
    id:   http://opaquenamespace.org/ns/rights/educational/
  - term: Orphan Works
    id  : http://opaquenamespace.org/ns/rights/orphan-work-us/
  - term: Free Access - No Re-Use
    id:   http://www.europeana.eu/rights/rr-f/
  - term: Rights Reserved - Restricted Access
    id:   http://www.europeana.eu/rights/rr-r/
  - term: Unknown
    id:   http://www.europeana.eu/rights/unknown/
