defaults: &defaults
  download_root: '/opt/download_root'
  pegasus_sru_endpoint: 'http://pegasus-test.library.ucsb.edu:5661'
  marmotta_host: localhost:8080
  internal_local_vocab_root: <%= ActiveFedora.fedora.host %>
development:
  <<: *defaults
test:
  <<: *defaults
production:
  <<: *defaults
  pegasus_sru_endpoint: 'http://pegasus.library.ucsb.edu:5661'
  internal_local_vocab_root: 'http://alexandria.ucsb.edu:8080/fedora/rest'
