#!/usr/bin/env ruby

filename = ARGV[0]

if filename.nil?
  puts "Usage: #{$PROGRAM_NAME} filename username"
  puts "Please provide the a file path you want to import."
  exit(1)
end

unless File.exists?(filename)
  puts "Unable to read file #{filename}"
  exit(1)
end


puts "Loading environment..."
require File.join(File.dirname(__FILE__), '../config/environment.rb')
require 'importer'
puts "Starting import..."

size = Importer::ModsImporter.new(filename).import_all

puts "Imported #{size} records."


